language: python
python:
    - 2.6
    - 2.7
    - 3.3

before_install:
    - pip install --quiet --use-mirrors coverage
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --quiet --use-mirrors unittest2; fi

install:
    - python setup.py install

script:
    - make test
    - coverage run --omit='*/site-packages/*,*/distutils/*' ./test/test.py
    - coverage report --show-missing

after_success:
    - pip install --quiet coveralls
    - coveralls
