language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx

install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then python setup.py bdist_rpm; fi
  - make install

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false

addons:
  apt:
    packages:
      - rpm
      - tcsh
