language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - pypy

before_install:
    - pip install --quiet coverage --use-mirrors

install:
    - python setup.py install

script:
    - make test
    - coverage run --omit='*/site-packages/*,*/distutils/*' ./test/test_argcomplete.py
    - coverage report --show-missing

after_success:
    - pip install --quiet coveralls
    - coveralls
