language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx

before_install:
  - pip --quiet install coverage pexpect

install:
  - pip install flake8
  - python setup.py build
  - python setup.py sdist
  - python setup.py bdist
  - python setup.py bdist_rpm
  - python setup.py install

script:
  - make lint
  - coverage run --source=argcomplete ./test/test.py

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - python: 3.2
    - python: pypy

sudo: false

addons:
  apt:
    packages:
      - rpm
      - tcsh
