language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3

before_install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install unittest2; fi
    - pip --quiet install coverage

install:
    - python setup.py build
    - python setup.py sdist
    - python setup.py bdist
    - python setup.py bdist_rpm
    - python setup.py install

script:
    - make test
#    - coverage run --omit='*/site-packages/*,*/distutils/*' ./test/test.py
#    - coverage report --show-missing

#after_success:
#    - pip install --quiet coveralls
#    - coveralls

matrix:
  allow_failures:
    - python: 2.6
    - python: 3.2
    - python: pypy

sudo: false

addons:
  apt:
    packages:
      rpm
